### PR TITLE
Fixed semantic meaning

### PR DESCRIPTION
**Pull request by ajacques**
And meta tag

### CODE REVIEW

**Comment by ajacques** [comment]
By making "Hello world" an h1 we define the semantic meaning of the web page declaring that there is a header. Without it, it's just a dangling block of text that has no real meaning. ALL HAIL THE SEMANTIC WEB.

**Comment by ajacques** [comment]
I've updated the pull request with new commits that should merge cleanly. These also fix the newlines to be unix.

**Comment by ajacques** [comment]
Any updates? This is blocking my work on website migration.

**Comment by thescouser89** [comment]
I don't see any unit tests. Please add some unit tests.

**Comment by thescouser89** [comment]
Also please make sure you follow the convention regarding spaces and newline operators, so as not to create huge commit diffs. Thank you.

**Comment by gchaw** [comment]
Guys... Stahp!
Okay?

**Comment by ajacques** [comment]
## This change wasn't a tabs vs spaces change, it was me fixing newlines. The newlines used Windows newline format instead of the Git convention Linux newlines.

Adam Jacques
Sent from my mobile phone

-------- Original Message --------

**Comment by kurtkilpela** [comment]
+1

**Comment by gchaw** [comment]
Can't accept this based on the fact that you removed my ever so important quotation marks.

**Pull request closed without merging**
